mpi:
  - mpich
  - openmpi
c_compiler_version:
  - '7' # [linux64]
  - '7' # [linux64]
  - '7' # [linux64]
  - '7' # [linux64]
  - '7' # [linux64]
cxx_compiler_version:
  - '7' # [linux64]
  - '7' # [linux64]
  - '7' # [linux64]
  - '7' # [linux64]
  - '7' # [linux64]
