travis:
  secure:
    BINSTAR_TOKEN: grUtA99BiPRA//GH5ZyUACfNpkAPvZpRy5KZKsEhIscRf56BoRUakv8wNvUpIdnzjXm8nt91GUSeuXKGYM8d8+4MVBD0jeQd9mhDIfdJ9qsKiLgxgP+OdAkj3pVbbpW41T17qyh/lvHMDOEc4PwSTBA4+gZlgqphYm++tNx+0v5fIZeyp4M3dUIeoM5Z9gv8Ac5my+bS34Dpz9x7dKA75YpUpk9hjIyUeRq6BSRecQCh0MwzbHwfGPOfwEgRbt/IkTOuMkdhtM47527PLNqxOTRLDJzwd0N1riK/8FfqhHWLauBnB6U4cXx7BuguFLPbZWJqj30Rd3DcjRySsVAnxS+HnMEkd3q0FdEYVVxjFAhvMA/QTi/62cklg9bMdV23pQNWMhyTNiPlvpgJlYFl9pujNKrnMxhtkm28mL6EvB9QCUseSeZ6DsIXN0Lcj6vhhuS+9lEKAko1DG6TLYknQ153BcAMcMhY/2oArj3m59MMup7noh2EOuDP76ZhR/mCSMLuUOnDmCiA1rsbXdmTlI8VqqZGVFt8OcSMIOFVma2X5Zdlq/FX7QLnH0N19GLem96Gh//cJ4TLR9VkOev0KXVhrv609QStd7nh2McgU5SrrOnwsjkS8MjozqYoJnfmWWwuv7cc7RTJTU9IjfPV7qMyQKjyUUN3bag0fM+6mFI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
